### ISSUE TITLE
New trackers request

### ISSUE THREAD

**Issue by duramato** [Coatt/Coatt#1]
I would love to see these added
BTDigg (api)
TorrentProject (api)
Torrentz (has searchable rss feed)
RARBG (api)
BitSnoop (searcable rss feed)

**Comment by PartTimeLegend** [comment]
I see absolutely no issue with adding these trackers. I'm going to spend the first portion of my time refactoring the application structure to Coatt rather than Jackett.

If you or anyone else is able to add these trackers and issue pull requests they are more than welcome.

**Comment by rarbg** [comment]
@PartTimeLegend 
RARBG is already integrated into Jackett , its just that Jackett is using a deprecated api, it just needs to be updated

**Comment by duramato** [comment]
@rarbg That is the old jackett that is no longer maintained , the new team removed rarbg from jackett since they think "jackett shouldnt have public trackers to not promote piracy) thats where @PartTimeLegend  version comes , to bring back support to public trackers :)

**Comment by rarbg** [comment]
@duramato 
Still it will be a lot easier to copy the old code from jackett and modify it to comply with the new api we have :P

**Comment by PartTimeLegend** [comment]
@rarbg Since you know your new API why not submit a pull now and I'll accept it? Problem solved and you're back on the list.

I saw Jackett as a means to add additional trackers, a Coatt is bigger than a jacket so we can get more in.

I can look at updating it in a few hours, but I have this pesky 9to5 thing I need to do in the meantime.

**Comment by PartTimeLegend** [comment]
No pull request issued. Closing.

**Comment by duramato** [comment]
Its a request ,not an statment that i was going to do it.
