### ISSUE TITLE
Updates...

### ISSUE THREAD

**Issue by Kyzoku** [Coatt/Coatt#3]
Are you still working on this project?  I found out about your project a week ago, when I found that Jackett didn't support public trackers.  Honestly, I think the reason for them not doing so is a very dumb one, but their choice regardless.  I am not able to contribute as I have 0 programming skill and this website alone is one of the most baffling I've come across :).  I just want you to know that their are people out there who feel as you do and would like public tracker support.

**Comment by PartTimeLegend** [comment]
There are lots of plans in refactoring the project, however they take a significant amount of time.

The main first task is the rebranding away from Jackett and to Coatt. This is currently undergoing testing on my own servers, and patches being brought inline. I hope to be able to issue a release soon^TM.

**Comment by tizmagik** [comment]
Thanks for this fork. Is there anything specific you need help with?

**Comment by PartTimeLegend** [comment]
@tizmagik I need time and a few helpful hands. Want to help out?
