### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Deftinw0lf** [Coatt/Coatt#5]
Not super experienced with this sort of thing, but I haven't been able to get this installed by building with Visual Studio as I was able to with some of the older Jackett installations.

Just trying to get something running that will support all of the trackers I was using, right now the main one that I'm missing is animetorrents.me. 

Thanks for the support, sorry if it's a stupid issue.

**Comment by PartTimeLegend** [comment]
I'm in the process of rebranding. Unfortunately I'm a little busy, so I'm pushing changes as I do them.

The build is currently failing, so I'm planning to try and get a running build this weekend.

**Comment by poplolnman** [comment]
How does one run this one and the Jackett fork at the same time on windows or does this support both public and private trackers?
